# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: setup CI
        
      # echo dir
      - name: Echo dir
        working-directory: ./Dropspot
        run: echo $PWD
      
      # show content
      - name: dir content
        working-directory: ./Dropspot
        run: ls -a
      
        # make gradlew executable
      - name: Make gradlew executable
        working-directory: ./Dropspot
        run: chmod +x gradlew
        
      # show available tasks
      - name: Show available tasks
        working-directory: ./Dropspot
        run: ./gradlew tasks
        
      # Build the application and invoke both the assemble and check tasks
      - name: Execute the build
        working-directory: ./Dropspot
        run: ./gradlew build
      

